CREATE table users (
id INTEGER NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
salt VARCHAR(512) NOT NULL,
password VARCHAR(1024) NOT NULL,
createdAt DATE NOT NULL,
updatedAt DATE NOT NULL
);


